FROM node:alpine

WORKDIR '/app'

COPY ./package.json ./
RUN npm install -g npm-check-updates
RUN ncu -u  --packageFile package.json
RUN npm update
RUN npm install

COPY ./ ./

CMD ["npm", "run","start"]
